#!/bin/bash

## load library
export PROFILER=$2
export ORDOPATH="$(pwd)/ordo/"

source "$ORDOPATH/library/auxiler";


if [[ $1 == "rebase" ]];then
    blackbird_rebased
fi

if [[ $1 == "install" ]];then
    blackbird_install
fi


if [[ $1 == "reset" ]];then
    blackbird_recover
fi