#!/bin/bash

## load library
export BBPROFILE=$2
export BPAT=$(pwd)
source "$BPAT/bind/library/auxiler";


if [[ $1 == "rebase" ]];then
    blackbird_rebased
fi

if [[ $1 == "install" ]];then
    blackbird_install
fi


if [[ $1 == "reset" ]];then
    blackbird_recover
fi