#!/bin/bash


##
## OPERASI INI DIGUNAKAN UNTUK HARDISK BARU 
## 1. PERANGKAT BARU
## 2. RECOVERY TOTAL


## load library
BPAT=$(pwd)
source "$BPAT/bind/library/auxiler";






function blackbird_rebased_prepare() {
    blackbird_storage_unmonted
    blackbird_storage_purelvm2
    blackbird_storage_tearluks
}


function blackbird_rebased() {

    blackbird_rebased_prepare
   
}


