#!/bin/bash

## STORAGE PROTOCOL BLACKBIRD LEVEL 1
## lead : AL Muhdil Karim
## team : -




##
## REGISTER PACKS
blackbird_regpack_main "xfsprogs lvm2"


##
## PREPARRING STORAGE



##
## MAIN FUNCTION
function blackbird_storage_protocol_base() {

}


function blackbird_storage_protocol_make() {

}


function blackbird_storage_protocol_reco() {

}