#!/bin/bash


##
## OPERASI INI DIGUNAKAN UNTUK HARDISK BARU 
## 1. PERANGKAT BARU
## 2. RECOVERY TOTAL


## load library
BPAT=$(pwd)
source "$BPAT/bind/library/auxiler";


function blackbird_rebased() {

    #blackbird_auxiler_prepare_libs
   
}


