#!/bin/bash


##
## OPERASI INI DIGUNAKAN UNTUK HARDISK BARU 
## 1. PERANGKAT BARU
## 2. RECOVERY TOTAL


## load library
BPAT=/ordo
source "$BPAT/bind/library/auxiler";


function blackbird_rebased() {

    clear
    echo 'starting recovery procedure ...'
    sleep 1
    blackbird_unpacks_prepare_main
    blackbird_systems_prepare_main
    blackbird_storage_prepare_base
    blackbird_systems_install_base
}

