#!/bin/bash


##
## OPERASI INI DIGUNAKAN UNTUK INSTALL ULANG TANPA MERUBAH PARTISI YANG TELAH ADA DAN TANPA MELAKUKAN FORMAT PADA STORAGE DATA


## load library
BPAT=$(pwd)
source "$BPAT/bind/library/auxiler";


function blackbird_recover() {
    clear
    echo 'starting recovery procedure ...'
    sleep 1
    blackbird_unpacks_prepare_main
    blackbird_systems_prepare_main
    blackbird_storage_prepare_reco
    blackbird_systems_install_reco
}