#!/bin/bash


function blackbird_rebased_prepare() {
    blackbird_storage_unmonted
    blackbird_storage_purelvm2
    blackbird_storage_tearluks
}


function blackbird_rebased() {
    blackbird_sysinfo_main
    #blackbird_rebased_prepare
   
}
